"""'initial'

Revision ID: 2cc33a09fb6a
Revises:
Create Date: 2024-10-21 00:33:19.015172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc33a09fb6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('legs', 'breast', 'back', 'shoulders', 'biceps', 'triceps', 'press', 'stretching', 'MFR', name='category'), nullable=False),
    sa.Column('button_name', sa.String(), nullable=False),
    sa.Column('video', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['video'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('main_menu', 'training', 'gym_training', 'change_gym_training', 'load_gym_training', 'home_training', 'change_home_training', 'training_profile', 'change_profile', 'male', 'female', 'gain_muscle_mass', 'weight_loss', 'maintaining_muscle_mass', 'workouts_2', 'workouts_3', 'add_training_record', 'get_training_record', 'necessary_equipment', 'change_necessary_equipment', 'base_of_exercises', 'legs', 'breast', 'back', 'shoulders', 'biceps', 'triceps', 'press', 'stretching', 'MFR', 'add_exercise_video', 'exercises_video', 'tariffs', 'tarif1', 'tarif2', 'manual', name='state'), nullable=False),
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('purpose', sa.Enum('gain_muscle_mass', 'weight_loss', 'maintaining_muscle_mass', name='purpose'), nullable=False),
    sa.Column('number_of_training', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_profiles')
    op.drop_table('journals')
    op.drop_table('users')
    op.drop_table('exercises')
    op.drop_table('videos')
    op.drop_table('tariffs')
    op.drop_table('images')
    op.drop_table('admins')
    op.execute("DROP TYPE category")
    op.execute("DROP TYPE state")
    op.execute("DROP TYPE gender")
    op.execute("DROP TYPE purpose")
    # ### end Alembic commands ###
